package warehouse.frontend;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeForm() {
        initComponents();
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Check if the window is maximized
                if ((getExtendedState() & MAXIMIZED_BOTH) == MAXIMIZED_BOTH) {
                    // Set background color of JFrame when maximized
                    getContentPane().setBackground(new Color(0, 51, 51));
                    // Center jPanel1
                    Container.setLocation((getWidth() - Container.getWidth()) / 2,
                            (getHeight() - Container.getHeight()) / 2);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JButton();
        contactusbtn = new javax.swing.JButton();
        userbtn = new javax.swing.JButton();
        Orderbtn = new javax.swing.JButton();
        customerbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        productbtn = new javax.swing.JButton();
        Categorybtn = new javax.swing.JButton();
        Incomingstockbtn = new javax.swing.JButton();
        Soldbtn = new javax.swing.JButton();
        Stockbtn = new javax.swing.JButton();
        Reportbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        Container.setBackground(new java.awt.Color(0, 102, 102));
        Container.setPreferredSize(new java.awt.Dimension(800, 500));

        logoutbtn.setBackground(new java.awt.Color(204, 0, 0));
        logoutbtn.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 0));
        logoutbtn.setText("LOGOUT");
        logoutbtn.setBorder(null);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        contactusbtn.setBackground(new java.awt.Color(0, 102, 102));
        contactusbtn.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        contactusbtn.setForeground(new java.awt.Color(242, 242, 242));
        contactusbtn.setText("Contact Us");
        contactusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeForm.this.actionPerformed(evt);
            }
        });

        userbtn.setBackground(new java.awt.Color(0, 102, 102));
        userbtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        userbtn.setText("USER ");
        userbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        userbtn.setBorderPainted(false);
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });

        Orderbtn.setBackground(new java.awt.Color(0, 102, 102));
        Orderbtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        Orderbtn.setText("ORDER");
        Orderbtn.setBorderPainted(false);
        Orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderbtnActionPerformed(evt);
            }
        });

        customerbtn.setBackground(new java.awt.Color(0, 102, 102));
        customerbtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        customerbtn.setText("CUSTOMER");
        customerbtn.setBorderPainted(false);
        customerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans CJK KR", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("WAREHOUSE PRODUCT MOVEMENT SYSTEM\n");

        productbtn.setBackground(new java.awt.Color(0, 102, 102));
        productbtn.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        productbtn.setText("PRODUCT");
        productbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        productbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productbtnActionPerformed(evt);
            }
        });

        Categorybtn.setBackground(new java.awt.Color(0, 102, 102));
        Categorybtn.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        Categorybtn.setText("CATEGORY ");
        Categorybtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Categorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategorybtnActionPerformed(evt);
            }
        });

        Incomingstockbtn.setBackground(new java.awt.Color(0, 102, 102));
        Incomingstockbtn.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        Incomingstockbtn.setText("RECORD INCOMING STOCK");
        Incomingstockbtn.setBorder(null);
        Incomingstockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomingstockbtnActionPerformed(evt);
            }
        });

        Soldbtn.setBackground(new java.awt.Color(0, 102, 102));
        Soldbtn.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        Soldbtn.setText("RECORD SOLD STOCK");
        Soldbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Soldbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldbtnActionPerformed(evt);
            }
        });

        Stockbtn.setBackground(new java.awt.Color(0, 102, 102));
        Stockbtn.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        Stockbtn.setText("STOCK DIFFERENCE");
        Stockbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Reportbtn.setBackground(new java.awt.Color(0, 102, 102));
        Reportbtn.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        Reportbtn.setText("DELIVERY REPORT");
        Reportbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(199, 199, 199))
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Orderbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbtn)
                .addGap(333, 333, 333))
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(contactusbtn))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Categorybtn)
                                    .addGroup(ContainerLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(userbtn))
                                    .addComponent(productbtn)))
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(customerbtn)))
                        .addGap(94, 94, 94)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Stockbtn)
                            .addComponent(Soldbtn)
                            .addComponent(Incomingstockbtn)
                            .addComponent(Reportbtn))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userbtn)
                    .addComponent(Incomingstockbtn))
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Categorybtn)
                        .addGap(31, 31, 31)
                        .addComponent(productbtn)
                        .addGap(1, 1, 1))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Soldbtn)
                        .addGap(31, 31, 31)
                        .addComponent(Stockbtn)))
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Reportbtn))
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(customerbtn)))
                        .addGap(18, 18, 18)
                        .addComponent(Orderbtn)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(logoutbtn))
                .addGap(16, 16, 16)
                .addComponent(contactusbtn)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 618, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:

        Login loginFrame = new Login();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        // TODO add your handling code here:
        ContactUs contactusframe = new ContactUs();
        contactusframe.setVisible(true);
        contactusframe.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_actionPerformed

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        // TODO add your handling code here:
        ManageUser manageuser = new ManageUser();
        manageuser.setVisible(true);
        manageuser.setLocationRelativeTo(null);
        this.dispose();


    }//GEN-LAST:event_userbtnActionPerformed

    private void OrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OrderbtnActionPerformed

    private void productbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productbtnActionPerformed
        // TODO add your handling code here:
        Product1 product1frame=new Product1();
        product1frame.setVisible(true);
        product1frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_productbtnActionPerformed

    private void customerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerbtnActionPerformed
        // TODO add your handling code here:
        Customerform customerformframe=new Customerform();
        customerformframe.setVisible(true);
        customerformframe.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_customerbtnActionPerformed

    private void CategorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategorybtnActionPerformed
        // TODO add your handling code here:
        Category categoryframe = new Category();
        categoryframe.setVisible(true);
        categoryframe.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_CategorybtnActionPerformed

    private void IncomingstockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomingstockbtnActionPerformed
        // TODO add your handling code here:
        RecordIncomingStock recordincomingstock = new RecordIncomingStock();
        recordincomingstock.setVisible(true);
        recordincomingstock.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_IncomingstockbtnActionPerformed

    private void SoldbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldbtnActionPerformed
        // TODO add your handling code here:
        RecordSoldStock recordsoldstock = new RecordSoldStock();
        recordsoldstock.setVisible(true);
        recordsoldstock.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SoldbtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Categorybtn;
    private javax.swing.JPanel Container;
    private javax.swing.JButton Incomingstockbtn;
    private javax.swing.JButton Orderbtn;
    private javax.swing.JButton Reportbtn;
    private javax.swing.JButton Soldbtn;
    private javax.swing.JButton Stockbtn;
    private javax.swing.JButton contactusbtn;
    private javax.swing.JButton customerbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton productbtn;
    private javax.swing.JButton userbtn;
    // End of variables declaration//GEN-END:variables
}
