package warehouse.frontend;

import warehouse.backend.UserDAO;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Check if the window is maximized
                if ((getExtendedState() & MAXIMIZED_BOTH) == MAXIMIZED_BOTH) {
                    // Set background color of JFrame when maximized
                    getContentPane().setBackground(new Color(0, 51, 51));
                    // Center jPanel1
                    Container.setLocation((getWidth() - Container.getWidth()) / 2,
                            (getHeight() - Container.getHeight()) / 2);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        Account = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Idno = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Userphone = new javax.swing.JLabel();
        Registerbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Loginbutton = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtIdno = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelephoneno = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");
        setBackground(new java.awt.Color(255, 255, 255));

        Container.setBackground(new java.awt.Color(0, 102, 102));
        Container.setMaximumSize(new java.awt.Dimension(500, 600));
        Container.setPreferredSize(new java.awt.Dimension(500, 600));

        Account.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("CREATE ACCOUNT");

        Username.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Name");

        Idno.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Idno.setForeground(new java.awt.Color(255, 255, 255));
        Idno.setText("ID Number");

        Email.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(242, 242, 242));
        Email.setText("Email");

        Userphone.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Userphone.setForeground(new java.awt.Color(255, 255, 255));
        Userphone.setText("Telephone No\n");

        Registerbutton.setBackground(new java.awt.Color(255, 0, 0));
        Registerbutton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Registerbutton.setForeground(new java.awt.Color(255, 255, 0));
        Registerbutton.setText("Register\n");
        Registerbutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbuttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Already have an Account?\n");

        Loginbutton.setBackground(new java.awt.Color(255, 0, 0));
        Loginbutton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Loginbutton.setForeground(new java.awt.Color(255, 255, 0));
        Loginbutton.setText("Login");
        Loginbutton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbuttonActionPerformed(evt);
            }
        });

        txtName.setBackground(new java.awt.Color(0, 102, 102));
        txtName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("\n");
        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        txtIdno.setBackground(new java.awt.Color(0, 102, 102));
        txtIdno.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtIdno.setForeground(new java.awt.Color(255, 255, 255));
        txtIdno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        txtEmail.setBackground(new java.awt.Color(0, 102, 102));
        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 2));

        txtTelephoneno.setBackground(new java.awt.Color(0, 102, 102));
        txtTelephoneno.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTelephoneno.setForeground(new java.awt.Color(242, 242, 242));
        txtTelephoneno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 2));

        role.setBackground(new java.awt.Color(255, 0, 0));
        role.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 0));
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warehouse Manager", "Staff", "Customer", "Ship Carrier", " ", " " }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addComponent(Registerbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Loginbutton))
                            .addComponent(Email)
                            .addComponent(Userphone)
                            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTelephoneno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                        .addComponent(txtIdno, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(Idno)
                                    .addComponent(Username)))
                            .addComponent(Account)))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Account)
                .addGap(18, 18, 18)
                .addComponent(Username)
                .addGap(18, 18, 18)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(Idno)
                .addGap(36, 36, 36)
                .addComponent(txtIdno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Userphone)
                .addGap(18, 18, 18)
                .addComponent(txtTelephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registerbutton)
                    .addComponent(jLabel7)
                    .addComponent(Loginbutton))
                .addGap(18, 18, 18)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbuttonActionPerformed

    // Fetch user input from the text fields and role selection
    var username = Username.getText().toUpperCase().trim();
    var email = txtEmail.getText().toLowerCase().trim();
    var idno = Idno.getText();
    var userphone = Userphone.getText();
    var userrole = (String) role.getSelectedItem();

    // Check if any fields are empty (optional validation)
    if(username.isEmpty() || email.isEmpty() || idno.isEmpty() || userphone.isEmpty() || userrole.isEmpty()) {
        // Display an error message (optional)
        JOptionPane.showMessageDialog(this, "All fields are required!");
        return;
    }

    // Register user using the UserDAO and check the result
    boolean isInserted = UserDAO.insertUser(username, idno, email, userphone, userrole);
    
    if (isInserted) {
        // If user is successfully registered, show success message and open CreatePassword frame
        JOptionPane.showMessageDialog(this, "User registered successfully!");

        // Navigate to the next frame
        CreatePassword createpasswordFrame = new CreatePassword(email);
        createpasswordFrame.setVisible(true);
        createpasswordFrame.setLocationRelativeTo(null);
        this.dispose();
    } else {
        // If registration failed, show error message
        JOptionPane.showMessageDialog(this, "Error: User registration failed.");
    }

    }//GEN-LAST:event_RegisterbuttonActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void LoginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbuttonActionPerformed
        // TODO add your handling code here:
        
        Login loginFrame = new Login();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_LoginbuttonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Idno;
    private javax.swing.JButton Loginbutton;
    private javax.swing.JButton Registerbutton;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Userphone;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdno;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelephoneno;
    // End of variables declaration//GEN-END:variables
}
